databases:
  - name: managingapp_db
    databaseName: managingapp_db_1n1x
    user: managingapp_db_1n1x_user
    region: singapore

services:
  - type: web
    name: managing-app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        value: postgresql://managingapp_db_user:PwB2zSZjIaVksvUqh1OAqOjStp26v4rb@dpg-cv6jo252ng1s73fup68g-a/managingapp_dbpostgresql://managingapp_db_user:PwB2zSZjIaVksvUqh1OAqOjStp26v4rb@dpg-cv6jo252ng1s73fup68g-a/managingapp_db
        fromDatabase:
          name: managingapp_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

