databases:
  - name: managingapp_db
    databaseName: managingapp_db_1n1x
    user: managingapp_db_1n1x_user
    region: singapore

services:
  - type: web
    name: managing-app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        value: postgresql://managingapp_db_1n1x_user:TzK5vp1oj06MdzzeRme8p4nBybxwJj4w@dpg-cvtou6h5pdvs73due9dg-a/managingapp_db_1n1x
        fromDatabase:
          name: managingapp_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

